<template>
  <v-main>
    <v-app-bar
            app
            color="primary"
            dark
            clipped-left
    >
      <v-app-bar-nav-icon></v-app-bar-nav-icon>
      <v-toolbar-title style="width: 600px" class="ml-0 pl-4">
        <span class="hidden-sm-and-down">广州上腾仪器设备有限公司仪器云平台管理系统</span>
      </v-toolbar-title>

      <v-spacer></v-spacer>
      <v-btn
              text
              @click="handleQuit"
      >
        <span class="mr-2">退出</span>
        <v-icon>mdi-open-in-new</v-icon>
      </v-btn>
    </v-app-bar>
    <v-navigation-drawer permanent clipped app width="200">
      <v-list
              dense
              nav
              rounded
      >
	      <v-list-item-group
		      v-model="selectedItem"
		      color="primary"
	      >
		      <v-list-item
			      v-for="item in items"
			      v-show="item.role.includes(getItem('roleName'))"
			      :key="item.title"
			      link
			      @click="$router.push(item.route)"
		      >
			      <v-list-item-icon>
				      <v-icon>{{ item.icon }}</v-icon>
			      </v-list-item-icon>

			      <v-list-item-content>
				      <v-list-item-title>{{ item.title }}</v-list-item-title>
			      </v-list-item-content>
		      </v-list-item>
	      </v-list-item-group>
      </v-list>
    </v-navigation-drawer>
    <transition name="puff-in-center" mode="out-in">
      <router-view style="padding: 15px"></router-view>
    </transition>
  </v-main>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'Home',
  components: {

  },
  data () {
    return {
	    selectedItem: 0,
      items: [
        { title: '首页', icon: 'mdi-view-dashboard', route: '/index', role: ['admin', 'user', 'regionalAgent']},
        { title: '账号信息', icon: 'mdi-account', route: '/account-information', role: ['admin', 'user', 'regionalAgent'] },
        { title: '用户列表', icon: 'mdi-card-account-details-outline', route: '/user-list', role: ['admin', 'regionalAgent']},
        { title: '区域代理商', icon: 'mdi-view-carousel-outline', route: '/regional-agents', role: ['admin']},
        { title: '设备列表', icon: 'mdi-view-carousel-outline', route: '/device-list', role: ['user'] },
      ],
      right: null,
    }
  },
  methods: {
    handleQuit() {
      window.sessionStorage.clear()
      this.$store.commit('setReservedInfoList', [])
      this.$router.push('/login')
    }
  }
}
</script>

<style scoped>
  .puff-in-center-enter-active, .puff-in-center-leave-active {
    transition: all .25s ease-in-out;
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
  .puff-in-center-enter, .puff-in-center-leave-to /* .fade-leave-active below version 2.1.8 */ {
    transition: all .25s ease-in-out;
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
    -webkit-filter: blur(4px);
    filter: blur(4px);
    opacity: 0;
  }
  .puff-in-center {
    -webkit-animation: puff-in-center 0.2s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
    animation: puff-in-center 0.2s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-11-20 12:36:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation puff-in-center
   * ----------------------------------------
   */
  @-webkit-keyframes puff-in-center {
    0% {
      -webkit-transform: scale(2);
      transform: scale(2);
      -webkit-filter: blur(4px);
      filter: blur(4px);
      opacity: 0;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  }
  @keyframes puff-in-center {
    0% {
      -webkit-transform: scale(2);
      transform: scale(2);
      -webkit-filter: blur(4px);
      filter: blur(4px);
      opacity: 0;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  }

</style>
