<template>
  <v-main>
   <v-card
           class="mx-auto"
           elevation="5"
           width="400"
           :class="loginClass"
           @keydown.enter="handleLogin"
   >
     <v-card-title>
       云平台系统
     </v-card-title>
     <v-card-text>
       <v-form v-model="valid">
         <v-text-field
                 autofocus
                 v-model="username"
                 label="账号"
                 :rules="usernameRules"
                 hide-details="auto"
         ></v-text-field>
         <v-text-field
                 v-model="password"
                 label="密码"
                 :rules="passwordRules"
         ></v-text-field>
       </v-form>
     </v-card-text>
     <v-card-actions>
       <v-btn
               v-if="!isFail"
               color="info"
               block
               @click="handleLogin"
       >
         登录
       </v-btn>
       <v-btn
               v-else
               color="error"
               block
       >
         {{ loginMessage }}
       </v-btn>
     </v-card-actions>
   </v-card>
  </v-main>
</template>

<script>
  export default {
    name: "Login",
    data: () => ({
      isFail: false,
      valid: false,
      loginMessage: '服务器错误',
      username: '',
      password: '',
      usernameRules: [
        value => (value && value.length >= 1 && value.length <= 24) || '字符长度为 1~24',
        value => !(/[^a-zA-Z0-9]/.exec(value)) || '需使用数字、英文，不能使用特殊符号'
      ],
      passwordRules: [
        value => (value && value.length >= 5 && value.length <= 12) || '字符长度为 5~12',
        value => !(/[^a-zA-Z0-9]/.exec(value)) || '需使用数字、英文，不能使用特殊符号'
      ],
    }),
    computed: {
      loginClass() {
        return this.isFail ? ['wobble-hor-bottom'] : []
      }
    },
    methods: {
      handleLogin() {
        if (!this.valid) {
          !this.isFail && (this.isFail = true)
          this.loginMessage = '输入格式有误'
          setTimeout(() => {
            this.isFail && (this.isFail = false)
          }, 800)
          return
        }
        this.$axios.post('/login', {
          username: this.username,
          password: this.password
        })
        .then(({ headers: { authorization }, data: {code, data, message}}) => {
          console.log('code', code)
          console.log('data', data)
          console.log('message', message)
          console.log('authorization', authorization)
          if (!code) {
            const { roleName, user: {name, userId, userNumber, username, contact }} = data
            this.saveItem('roleName', roleName)
              .saveItem('name', name)
              .saveItem('userId', userId)
              .saveItem('userNumber', userNumber)
              .saveItem('username', username)
              .saveItem('contact', contact)
              .saveItem('token', authorization)

            this.$router.push('/')
          } else {
            this.loginMessage = message
            !this.isFail && (this.isFail = true)
          }
        })
        .catch(error => {
          this.loginMessage = '服务器错误'
          !this.isFail && (this.isFail = true)
          console.log('error', error)
        })
        .finally(() => {
          setTimeout(() => {
            this.isFail && (this.isFail = false)
          }, 800)
        })
      },
    }
  }
</script>

<style scoped>
 main{
   height: 100vh;
   display: flex;
   justify-content: center;
   align-items: center;
   background-image: url("../assets/images/loginBG.png");
   background-size: cover;
 }
 /* ----------------------------------------------
 * Generated by Animista on 2020-11-20 11:6:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

 /**
  * ----------------------------------------
  * animation wobble-hor-bottom
  * ----------------------------------------
  */
 @-webkit-keyframes wobble-hor-bottom {
   0%,
   100% {
     -webkit-transform: translateX(0%);
     transform: translateX(0%);
     -webkit-transform-origin: 50% 50%;
     transform-origin: 50% 50%;
   }
   15% {
     -webkit-transform: translateX(-30px) rotate(-6deg);
     transform: translateX(-30px) rotate(-6deg);
   }
   30% {
     -webkit-transform: translateX(15px) rotate(6deg);
     transform: translateX(15px) rotate(6deg);
   }
   45% {
     -webkit-transform: translateX(-15px) rotate(-3.6deg);
     transform: translateX(-15px) rotate(-3.6deg);
   }
   60% {
     -webkit-transform: translateX(9px) rotate(2.4deg);
     transform: translateX(9px) rotate(2.4deg);
   }
   75% {
     -webkit-transform: translateX(-6px) rotate(-1.2deg);
     transform: translateX(-6px) rotate(-1.2deg);
   }
 }
 @keyframes wobble-hor-bottom {
   0%,
   100% {
     -webkit-transform: translateX(0%);
     transform: translateX(0%);
     -webkit-transform-origin: 50% 50%;
     transform-origin: 50% 50%;
   }
   15% {
     -webkit-transform: translateX(-30px) rotate(-6deg);
     transform: translateX(-30px) rotate(-6deg);
   }
   30% {
     -webkit-transform: translateX(15px) rotate(6deg);
     transform: translateX(15px) rotate(6deg);
   }
   45% {
     -webkit-transform: translateX(-15px) rotate(-3.6deg);
     transform: translateX(-15px) rotate(-3.6deg);
   }
   60% {
     -webkit-transform: translateX(9px) rotate(2.4deg);
     transform: translateX(9px) rotate(2.4deg);
   }
   75% {
     -webkit-transform: translateX(-6px) rotate(-1.2deg);
     transform: translateX(-6px) rotate(-1.2deg);
   }
 }

 .wobble-hor-bottom {
   -webkit-animation: wobble-hor-bottom 0.8s both;
   animation: wobble-hor-bottom 0.8s both;
 }
</style>
